version: 2
jobs:
  install:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/petfinder-php
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer update --prefer-dist --optimize-autoloader --no-progress --no-interaction
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - vendor
  lint:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/petfinder-php
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no
      - run: vendor/bin/phpstan analyse --no-progress
  test-php73:
    docker:
      - image: circleci/php:7.3
    working_directory: ~/petfinder-php
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: vendor/bin/phpunit --colors=never --log-junit build/phpunit/results73.xml --coverage-html build/coverage --coverage-clover build/clover.xml
      - run: vendor/bin/php-coveralls -x build/clover.xml -o build/coveralls.json || true
      - store_artifacts:
          path: build/coverage
          prefix: coverage
      - store_test_results:
          path: build
  test-php72:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/petfinder-php
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: vendor/bin/phpunit --colors=never --log-junit build/phpunit/results72.xml
      - store_test_results:
          path: build
workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test-php73:
          requires:
            - install
      - test-php72:
          requires:
            - install
